package com.beegfs.admon.gui.components.internalframes.management;

import com.beegfs.admon.gui.common.XMLParser;
import com.beegfs.admon.gui.common.enums.NodeTypesEnum;
import com.beegfs.admon.gui.common.exceptions.CommunicationException;
import com.beegfs.admon.gui.common.tools.GuiTk;
import com.beegfs.admon.gui.common.tools.HttpTk;
import com.beegfs.admon.gui.components.internalframes.JInternalFrameInterface;
import com.beegfs.admon.gui.components.managers.FrameManager;
import java.util.ArrayList;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;


public class JInternalFrameRemoteLogFiles extends javax.swing.JInternalFrame
   implements JInternalFrameInterface
{
   private static final long serialVersionUID = 1L;

   static final Logger logger = Logger.getLogger(
      JInternalFrameRemoteLogFiles.class.getCanonicalName());

   private static final String getLogfileBaseUrl = HttpTk.generateAdmonUrl("/XML_GetLogFile");

   private ArrayList<TreeMap<String, String>> mgmtdNodes;
   private ArrayList<TreeMap<String, String>> metaNodes;
   private ArrayList<TreeMap<String, String>> storageNodes;
   private ArrayList<TreeMap<String, String>> clientNodes;
   private ArrayList<TreeMap<String, String>> admonNodes;

   public JInternalFrameRemoteLogFiles(XMLParser nodeListparser)
   {
      try
      {
         mgmtdNodes = nodeListparser.getVectorOfAttributeTreeMaps(
            NodeTypesEnum.MANAGMENT.shortType());
         metaNodes = nodeListparser.getVectorOfAttributeTreeMaps(
            NodeTypesEnum.METADATA.shortType());
         storageNodes = nodeListparser.getVectorOfAttributeTreeMaps(
            NodeTypesEnum.STORAGE.shortType());
         admonNodes = nodeListparser.getVectorOfAttributeTreeMaps(
            NodeTypesEnum.ADMON.shortType());
         clientNodes = nodeListparser.getVectorOfAttributeTreeMaps(
            NodeTypesEnum.CLIENT.shortType());
      }
      catch (CommunicationException ex)
      {
         logger.log(Level.SEVERE, "Communication error", ex);
      }

      if(mgmtdNodes == null)
      {
         mgmtdNodes = new ArrayList<>(0);
      }
      if(metaNodes == null)
      {
         metaNodes = new ArrayList<>(0);
      }
      if(storageNodes == null)
      {
         storageNodes = new ArrayList<>(0);
      }
      if(admonNodes == null)
      {
         admonNodes = new ArrayList<>(0);
      }
      if(clientNodes == null)
      {
         clientNodes = new ArrayList<>(0);
      }

      initComponents();
      setTitle(getFrameTitle());
      setFrameIcon(GuiTk.getFrameIcon());
   }

   @Override
   public boolean isEqual(JInternalFrameInterface obj)
   {
      return obj instanceof JInternalFrameRemoteLogFiles;
   }

   @Override
   public final String getFrameTitle()
   {
      return "Log Files";
   }

   /**
    * This method is called from within the constructor to initialize the form. WARNING: Do NOT
    * modify this code. The content of this method is always regenerated by the Form Editor.
    */
   @SuppressWarnings("unchecked")
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents()
   {

      jScrollPaneFrame = new javax.swing.JScrollPane();
      jPanelFrame = new javax.swing.JPanel();
      jTabbedPaneChooser = new javax.swing.JTabbedPane();
      remoteLogFileTabPanelMgmtd = new com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel(NodeTypesEnum.MANAGMENT, mgmtdNodes, getLogfileBaseUrl);
      remoteLogFileTabPanelMeta = new com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel(NodeTypesEnum.METADATA, metaNodes, getLogfileBaseUrl);
      remoteLogFileTabPanelStorage = new com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel(NodeTypesEnum.STORAGE, storageNodes, getLogfileBaseUrl);
      remoteLogFileTabPanelAdmon = new com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel(NodeTypesEnum.ADMON, admonNodes, getLogfileBaseUrl);
      remoteLogFileTabPanelClient = new com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel(NodeTypesEnum.CLIENT, clientNodes, getLogfileBaseUrl);

      setClosable(true);
      setResizable(true);
      addInternalFrameListener(new javax.swing.event.InternalFrameListener()
      {
         public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt)
         {
         }
         public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt)
         {
         }
         public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt)
         {
            formInternalFrameClosed(evt);
         }
         public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt)
         {
         }
         public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt)
         {
         }
         public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt)
         {
         }
         public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt)
         {
         }
      });

      jPanelFrame.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
      jPanelFrame.setPreferredSize(new java.awt.Dimension(867, 348));
      jPanelFrame.setLayout(new java.awt.BorderLayout(5, 5));

      jTabbedPaneChooser.addTab("Management Daemon", remoteLogFileTabPanelMgmtd);
      jTabbedPaneChooser.addTab("Metadata Daemon", remoteLogFileTabPanelMeta);
      jTabbedPaneChooser.addTab("Storage Daemon", remoteLogFileTabPanelStorage);
      jTabbedPaneChooser.addTab("Admon Daemon", remoteLogFileTabPanelAdmon);
      jTabbedPaneChooser.addTab("Client", remoteLogFileTabPanelClient);

      jPanelFrame.add(jTabbedPaneChooser, java.awt.BorderLayout.CENTER);
      jTabbedPaneChooser.getAccessibleContext().setAccessibleName("");

      jScrollPaneFrame.setViewportView(jPanelFrame);

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPaneFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 873, Short.MAX_VALUE)
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addComponent(jScrollPaneFrame, javax.swing.GroupLayout.DEFAULT_SIZE, 366, Short.MAX_VALUE)
      );

      pack();
   }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
      FrameManager.delFrame(this);
    }//GEN-LAST:event_formInternalFrameClosed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JPanel jPanelFrame;
   private javax.swing.JScrollPane jScrollPaneFrame;
   private javax.swing.JTabbedPane jTabbedPaneChooser;
   private com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel remoteLogFileTabPanelAdmon;
   private com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel remoteLogFileTabPanelClient;
   private com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel remoteLogFileTabPanelMeta;
   private com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel remoteLogFileTabPanelMgmtd;
   private com.beegfs.admon.gui.components.panels.RemoteLogFileTabPanel remoteLogFileTabPanelStorage;
   // End of variables declaration//GEN-END:variables
}
